apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { .Values.component } }
  labels:
    component: { { .Values.component } }
spec:
  # modify replicas according to your case
  replicas: 4
  selector:
    matchLabels:
      component: { { .Values.component } }
  template:
    metadata:
      labels:
        component: { { .Values.component } }
    spec:
      containers:
        - name: { { .Values.component } }
          image: rkalluru/{ { .Values.component } }
---