apiVersion: v1
kind: Service
metadata:
  name: {{.Values.component}}-roboshop
spec:
  type: NodePort
  selector:
    component: {{.Values.component}}
  ports:
    - protocol : TCP
      port: 80
      targetPort: 80