apiVersion: apps/v1
kind: Pod
metadata:
  name: frontend
  labels:
    component: frontend
spec:
  containers:
    - name : frontend
      image: rkalluru/frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    component: frontend
spec:
  # modify replicas according to your case
  replicas: 4
  selector:
    matchLabels:
      component: frontend
  template:
    metadata:
      labels:
        component: frontend
    spec:
      containers:
        - name: frontend
          image: rkalluru/frontend
