apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
    - name : frontend
      image: rkalluru/frontend
---
apiVersion: v1
kind: Pod
metadata:
  name: catalogue
spec:
  containers:
    - name : frontend
      image: rkalluru/catalogue
---
apiVersion: v1
kind: Pod
metadata:
  name: cart
spec:
  containers:
    - name : frontend
      image: rkalluru/cart
---
apiVersion: v1
kind: Pod
metadata:
  name: user
spec:
  containers:
    - name : frontend
      image: rkalluru/user
---
apiVersion: v1
kind: Pod
metadata:
  name: shipping
spec:
  containers:
    - name : frontend
      image: rkalluru/shipping
---
apiVersion: v1
kind: Pod
metadata:
  name: payment
spec:
  containers:
    - name : frontend
      image: rkalluru/payment
---
